### ISSUE TITLE
在线预览异常

### ISSUE THREAD

**Issue by M-cheng-web** [xun082/online-cooperative-edit#3]
抱歉，我这边点击在线预览发现无法正常展示页面，只有一个登录按钮且点击无反应

**Comment by xun082** [comment]
这个问题已知晓，本地是没问题的，问题正在排查，谢谢反馈

**Comment by xun082** [comment]
> 抱歉，我这边点击在线预览发现无法正常展示页面，只有一个登录按钮且点击无反应

看看最新的，已经解决了
